/**
 * skill-tree.js — Interactive skill tree visualization
 */
import store from '../store.js';

export function renderSkillTree(params, container) {
  container.innerHTML = `
    <div class="page animate-fade-in">
      <h1>Skill Tree</h1>
      <p style="color: var(--text-secondary); margin-bottom: 24px;">Master physics through skill progression. Complete prerequisites to unlock new content.</p>

      <div style="background: var(--bg-card); border-radius: var(--border-radius); padding: 16px; margin-bottom: 24px;">
        <h3>How it works:</h3>
        <ul style="color: var(--text-secondary); line-height: 1.8;">
          <li>🟢 <strong>Green nodes</strong> = Available to start</li>
          <li>🔵 <strong>Blue nodes</strong> = Currently working on</li>
          <li>⭐ <strong>Gold nodes</strong> = Completed</li>
          <li>🔒 <strong>Gray nodes</strong> = Locked (complete prerequisites first)</li>
          <li>⚔️ <strong>Red nodes</strong> = Boss battles</li>
        </ul>
      </div>

      <div style="overflow-x: auto;">
        <svg width="1200" height="600" style="border: 1px solid var(--accent-cyan); border-radius: var(--border-radius); background: var(--bg-primary);">
          <!-- Connections will be drawn here -->
          <defs>
            <style>
              .skill-node { cursor: pointer; transition: all 0.2s ease; }
              .skill-node:hover { filter: brightness(1.2); }
              .skill-node.completed { fill: var(--xp-gold); }
              .skill-node.available { fill: var(--accent-green); }
              .skill-node.locked { fill: var(--text-muted); }
              .skill-node-text { font-size: 10px; text-anchor: middle; dominant-baseline: middle; font-weight: bold; }
              .skill-connection { stroke: var(--accent-cyan); stroke-width: 2; fill: none; }
              .skill-connection.locked { stroke: var(--text-muted); }
            </style>
          </defs>

          <!-- SVG content generated by JavaScript below -->
        </svg>
      </div>

      <div style="margin-top: 32px; padding: 16px; background: var(--bg-card); border-radius: var(--border-radius);">
        <h3>Legend</h3>
        <p style="color: var(--text-secondary); margin: 0;">Complete lessons to progress through the skill tree. Boss battles mark the end of each unit section.</p>
      </div>
    </div>`;

  // Draw skill tree
  fetch('/data/skill-tree.json')
    .then(r => r.json())
    .then(data => {
      const svg = container.querySelector('svg');
      if (!svg) return;

      let allNodes = [];
      data.branches.forEach(branch => {
        allNodes = allNodes.concat(branch.nodes.map(n => ({ ...n, branchId: branch.id })));
      });

      // Draw connections
      allNodes.forEach(node => {
        node.prerequisites.forEach(prereqId => {
          const prereq = allNodes.find(n => n.id === prereqId);
          if (prereq) {
            const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
            line.setAttribute('x1', prereq.x + 30);
            line.setAttribute('y1', prereq.y + 30);
            line.setAttribute('x2', node.x + 30);
            line.setAttribute('y2', node.y + 30);
            line.setAttribute('class', `skill-connection ${isNodeUnlocked(node.id) ? '' : 'locked'}`);
            svg.appendChild(line);
          }
        });
      });

      // Draw nodes
      allNodes.forEach(node => {
        const group = document.createElementNS('http://www.w3.org/2000/svg', 'g');

        const circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
        circle.setAttribute('cx', node.x + 30);
        circle.setAttribute('cy', node.y + 30);
        circle.setAttribute('r', node.type === 'boss' ? 20 : 15);
        circle.setAttribute('class', `skill-node ${getNodeState(node.id)}`);
        circle.addEventListener('click', () => {
          if (node.type === 'lesson') {
            window.location.hash = `#/courses/mechanics/${node.lessonId}`;
          } else if (node.type === 'boss') {
            window.location.hash = `#/boss/${node.bossId}`;
          }
        });

        const text = document.createElementNS('http://www.w3.org/2000/svg', 'text');
        text.setAttribute('x', node.x + 30);
        text.setAttribute('y', node.y + 30);
        text.setAttribute('class', 'skill-node-text');
        text.setAttribute('fill', 'white');
        text.textContent = node.type === 'boss' ? '⚔️' : '✓';

        group.appendChild(circle);
        group.appendChild(text);
        svg.appendChild(group);
      });
    });
}

function isNodeUnlocked(nodeId) {
  return store.get(`courses.mechanics.lectures.${nodeId}.watched`) ||
         store.get(`courses.electromagnetism.lectures.${nodeId}.watched`) ||
         store.get(`courses.waves-quantum.lectures.${nodeId}.watched`);
}

function getNodeState(nodeId) {
  if (isNodeUnlocked(nodeId)) return 'completed';
  // TODO: Check if all prerequisites are complete
  return 'available';
}
